### ISSUE TITLE
Negative pressure warnings

### ISSUE THREAD

**Issue by chocolate-771** [glorialulu/wmoc#12]
Reproduce the example in the official document: Define background leak location, JUNCTION-22. When performing transient simulation, JUNCTION -29 has negative pressure, but the document can operate normally. Why?

**Comment by glorialulu** [comment]
Negative pressure warnings are generated when the piezometrix head inside pipe is lower than the elevation, i.e., pressure head is negative.

This can happen when the transient amplitude is large. The warnings are generated to inform users about the existence of negative pressure because:
1. Contamination intrusion may occur with the presence of pipe defects; however, in TSNet, **it is assumed that a backflow preventer is installed at each junction**, thus stopping any potential reverse flow.
2. When the pressure head is lower than vapor pressure, cavitation may happen. It is recommended that users inspect the nodes where negative pressure is present to examine whether the pressure is lower than vapor pressure. It should be noted that **cavitation is not modeled in TSNet**. Thus, if pressure is lower than vapor pressure, the results from TSNet may not be accurate.

The simulation can be performed with warnings.

**Comment by chocolate-771** [comment]
Thank you for your reply, I will check the nodes of the water supply network.
