### ISSUE TITLE
How to increase the maximum timestep while extracting velocity information every few meters over a large network.

### ISSUE THREAD

**Issue by IDoytchinov** [glorialulu/wmoc#21]
* tsnet version: 
* Python version:
* Operating System:

### Description
Dear Lu, et all. Me and Amine are attempting to model one of the local villages in Swiss (Verbier) networks with the software. The problem is as some of the pipes are quite short the maximum time step for our case is really really low - 0.00001. We as well wish to extract dynamics (velocities) through the length of the pipe. Thus we did naively by discretizing each longer pipe on many smaller pipes with nodes and using the nodes to extract velocities (as we want to study how the velocities propagate through the length of the pipe). Do you know how we can solve this time-step challenge? At the end of the day, the dynamics we will observe will be in the second's margin so 0.1 timestep for what we want to study is already enough we thought. Not sure how to make it less computationally intensive and if there is a smarter way than brute force and giant datasets? 

Thanks a lot for your kind help and advice!

Iordan Doytchinov, Ph.D.

Postdoctoral researcher and scientific collaborator 

Ecole Polytechnique Fédérale de Lausanne (EPFL)
EPFL – TOPO
Station 18 – Bâtiment GC C2 398

CH–1015 Lausanne

Office telephone: +41216939832
Personal mobile: +33699850592

iordan.doytchinov@epfl.ch
http://topo.epfl.ch/

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by glorialulu** [comment]
To answer your questions:

1. The time step in TSNet is determined by the shortest pipe. Please see the online documentation for more details. The reason why you have a very small timestep is likely because there are very short pipes in the network.
I would recommend evaluating whether those short pipes are really necessary for modeling purposes. Or whether it is tolerable to increase the length of those pipes. Once the lengths of the short pipes get increased, the timestep will get larger. 

2. Due to storage concerns, we opted to not store the results in the inner (discretized) nodes in TSNet. Thus, at this point I believe it is a viable and easy solution to manually add junctions at the locations where you want to access the results. It might be possible to get into the source codes and make some modifications to allow access to the inner nodes results in some specified pipes, but this change will require some effort. 

I am happy to chat with you on the project.  Please let me know if you have any other questions.


Best,
Lu
