### ISSUE TITLE
How pump inertia and rotation speed relate to the TSNet pump operation parameters

### ISSUE THREAD

**Issue by shenh** [glorialulu/wmoc#5]
Is there a way to relate pump inertia and rotational speed with pump shutoff/startup period, end open percentage, and the constant? Thanks

Hailiang

**Comment by glorialulu** [comment]
TSNet simulates controlled pump operations (shutoff/startup), not shut down due to power failure (for now).
During the controlled operation, the pump operation is defined by the operation curve which characterized how pump speed changes with time, so pump inertia and rotational speed do not come into the picture.

However, if the pump shutdown is due to power failure, then the operation curve(pump speed v.s. time) will be dependent on the pump inertia and rotational speed.

**Comment by wdvichete84** [comment]
@glorialulu that´s mean the start and shut down controlled could be perform by TSNet.
is that correct?

Also, is possible the shut down due to power failure could be represented including a valve and close very rapidly? 
make sense to you?
