### ISSUE TITLE
Default valve opening when initial status is closed

### ISSUE THREAD

**Issue by glorialulu** [glorialulu/wmoc#6]
Does the transient simulator default to every valve opening at t=0? I'm finding that if I omit the line that defines the valve opening:
```
tm.valve_opening('valve',[tc,ts,se,m])
```
then the valve opens at t=0, even when I explicitly define the network with the valve initial_status='Closed'. I'm expecting that if I omit the valve opening, then the valve should never open and the pressure should remain constant and flow-rate nearly zero.
I do find that if I set the valve opening to start at a time after the end of the simulation, then the valve never opens (as expected) and the solution is constant for pressure and nearly zero for flow-rate. When I do this workaround, I see a small nonzero flow-rate for a brief period of time, about 0.5 sec, at the beginning of the simulation. Perhaps this is just numerical noise?

_Originally posted by @Nathan-Becker in https://github.com/glorialulu/TSNet/issues/4#issuecomment-652819345_

**Comment by Nathan-Becker** [comment]
Any news on fixing this bug? I've done some more investigation, and I think I've uncovered some related symptoms. Maybe there are some helpful clues:

I found this description of the Fixed Status for the valve on p.73 of the EPANET manual:
```
Valve status at the start of the simulation. If set to OPEN or CLOSED then the control setting of the valve is ignored and the valve behaves as an open or closed link, respectively. If set to NONE, then the valve will behave as
intended. A valve's fixed status and its setting can be made to vary throughout a simulation by the use of control statements. If a valve's status was fixed to OPEN/CLOSED, then it can be made active again using a control that assigns a new numerical setting to it.
```

This led me to wonder if the valve control was being disabled when I set
```
wn.get_link('valve1').initial_status = wntr.network.elements.LinkStatus.Closed
```

Separately, I noticed that the Setting parameter of the valve didn't seem to be respected by the transient simulation. I was expecting that if I set a FCV valve to a particular setting then the flow-rate should match it.

The following test code might be revealing. There are two parameter settings at the top: valve_setting_gpm and initial_status_active. I looked at 2 cases:

1. If I set initial_status_active=True, then I think that is consistent with the EPANET manual's claim that the valve is allowed to operate via control messages. In that case, if I run the below script to the end, it prints out the initial flow-rate, and it is consistent with the valve_settting_gpm value. However, the final flow-rate (after the valve opens and reaches steady state) is not consistent with the valve_setting_gpm. And, there is some noisy ringing at the beginning of the transient simulation (shown in the plots that are generated). Maybe this ringing is caused by some sort of inconsistency between EPANET valve initial condition (which seems to respect the valve_setting parameter) and the transient simulator?
2. If I set initial_status_active=False, then the valve is forced closed at the beginning. The noisy ringing goes away, and the plots look qualitatively plausible. However, the valve_setting_gpm seems to have no effect on the steady-state flow-rate. I expected the steady-state flow-rate to match the valve_setting_gpm if the pump can support it.

```
# Define test-case options
valve_setting_gpm = 2.56
initial_status_active = True

# Initialize
import matplotlib
matplotlib.use('agg')
from matplotlib import pyplot as plt
import numpy
import pandas
import wntr
import tsnet


def gpm_to_m3s(gpm):
    return gpm/(60*264.172)

def m3s_to_gpm(m3s):
    return m3s*(60*264.172)

def m_to_psi(m):
    return m*1.4219702063247

def psi_to_m(psi):
    return psi/1.4219702063247

# New network
wn = wntr.network.WaterNetworkModel()

# Add water source --> reservoir at atmos, with a pump to get significant pressure
wn.add_reservoir('res', base_head=0)
wn.add_junction('in')
wn.add_pipe('source', start_node_name='res', end_node_name='in', length=40, diameter=0.03175)
wn.add_junction('pumpjunc')
pumpcurve = []
pumpcurve.append((gpm_to_m3s(0),psi_to_m(60)))
pumpcurve.append((gpm_to_m3s(5),psi_to_m(45)))
pumpcurve.append((gpm_to_m3s(10),psi_to_m(25)))
wn.add_curve('pumpcurve', 'HEAD', pumpcurve)
wn.add_pump(name='supply', start_node_name='in', end_node_name='pumpjunc', pump_type='HEAD', pump_parameter='pumpcurve')

# Add reference point junction 'ref'
wn.add_junction('ref')
wn.add_pipe('to_ref', start_node_name='pumpjunc', end_node_name='ref', length=10, diameter=0.03175)

# Add valve
wn.add_junction('before_valve1')
wn.add_pipe('to_valve1', start_node_name='ref', end_node_name='before_valve1', length=25, diameter=0.03175)
wn.add_junction('after_valve1')
wn.add_valve('valve1', start_node_name='before_valve1', end_node_name='after_valve1', valve_type='FCV', setting=gpm_to_m3s(valve_setting_gpm))
if initial_status_active:
    wn.get_link('valve1').initial_status = wntr.network.elements.LinkStatus.Active
else:
    wn.get_link('valve1').initial_status = wntr.network.elements.LinkStatus.Closed
wn.add_reservoir('atmos1', base_head=psi_to_m(0))
wn.add_pipe('out1', start_node_name='after_valve1', end_node_name='atmos1', length=15, diameter=0.03175/3)

# Prep plotting
fig = plt.figure(figsize=(8,5), dpi=80, facecolor='w', edgecolor='k')

# Build EPANET file
wn.write_inpfile('simp.inp')

# Construct transient model 
tm = tsnet.network.TransientModel('simp.inp')
tm.set_wavespeed(1200.) # m/s
tm.set_time(3) # simulation period [s]

# Set valve opening 
tc = 0.2 # valve opening period [s]
ts = 1 # valve opening start time [s]
se = 1 # end open percentage [s]
m = 1 # open constant [dimensionless]
tm.valve_opening('valve1',[tc,ts,se,m])

# Initialize and run simulation
tm = tsnet.simulation.Initializer(tm, 0, 'DD')
tm = tsnet.simulation.MOCSimulator(tm, 'simpres', 'unsteady')

# Gather results
t = tm.simulation_timestamps
ref_flow_rate = tm.get_link('to_ref').end_node_flowrate

# Prep plotting
fig = plt.figure(figsize=(8,5), dpi=80, facecolor='w', edgecolor='k')

# Plot flow-rates
plt.plot(t, m3s_to_gpm(ref_flow_rate), label='ref', linewidth=1.5)
plt.plot(t, m3s_to_gpm(tm.get_link('out1').end_node_flowrate), label='output1', linewidth=1.5)
plt.ylabel("flow-rate [gpm]")
plt.xlim([t[0],t[-1]])
plt.xlabel("Time [s]")
plt.legend(loc='best')
plt.draw()
plt.savefig('flowrate.png')

# Plot pressure
plt.clf()
plt.plot(t, m_to_psi(tm.get_node('ref').head), 'k', label='ref', linewidth=1.5)
plt.plot(t, m_to_psi(tm.get_node('after_valve1').head), label='output1', linewidth=1.5)
plt.ylabel("Pressure [PSI]")
plt.xlim([t[0],t[-1]])
plt.xlabel("Time [s]")
plt.legend(loc='best')
plt.draw()
plt.savefig('pressure.png')

print('Initial ref flow rate={}'.format(m3s_to_gpm(ref_flow_rate[0])))
print('Final ref flow rate={}'.format(m3s_to_gpm(ref_flow_rate[-1])))
```

**Comment by glorialulu** [comment]
The bug related to valve default status has been fixed and pushed to GitHub. I will look into the other issue later.
